@OfficeFlow_HostAddress = http://localhost:5119

GET {{OfficeFlow_HostAddress}}/api/user
Accept: application/json

###
GET {{OfficeFlow_HostAddress}}/api/user/12
Accept: application/json

###
POST {{OfficeFlow_HostAddress}}/api/user
Content-Type: application/json
Accept: application/json

{
    "First_name": "Essa",
    "Last_name": "Jaja",
    "Email": "essa@essa.com"
}

###
POST {{OfficeFlow_HostAddress}}/api/reservation
Content-Type: application/json
Accept: application/json

{
  "userId": 1,
  "deskId": 2,
  "startDate": "2026-05-16T08:00:00Z",
  "endDate": "2026-05-17T17:30:00Z"
}

###

GET {{OfficeFlow_HostAddress}}/api/reservation/available-terms?deskId=2&date=2026-05-19T15:00:00Z
Accept: application/json
