// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace OfficeFlow.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402230726_initMigration")]
    partial class initMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmenityDesk", b =>
                {
                    b.Property<int>("AmenitiesId")
                        .HasColumnType("integer");

                    b.Property<int>("DesksId")
                        .HasColumnType("integer");

                    b.HasKey("AmenitiesId", "DesksId");

                    b.HasIndex("DesksId");

                    b.ToTable("AmenityDesk");

                    b.HasData(
                        new
                        {
                            AmenitiesId = 1,
                            DesksId = 1
                        },
                        new
                        {
                            AmenitiesId = 2,
                            DesksId = 1
                        },
                        new
                        {
                            AmenitiesId = 1,
                            DesksId = 2
                        });
                });

            modelBuilder.Entity("OfficeFlow.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Monitor 4K"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Regulowane biurko"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fotel ergonomiczny"
                        });
                });

            modelBuilder.Entity("OfficeFlow.Models.Desk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Office_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Office_id");

                    b.ToTable("Desks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Office_id = 1,
                            Price = 50.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Office_id = 1,
                            Price = 100.00m,
                            Status = "Maintenance",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Office_id = 2,
                            Price = 60.00m,
                            Status = "Retired",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Office_id = 1,
                            Price = 44.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Office_id = 2,
                            Price = 45.00m,
                            Status = "Available",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Office_id = 1,
                            Price = 46.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Office_id = 2,
                            Price = 47.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Office_id = 1,
                            Price = 48.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Office_id = 2,
                            Price = 49.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Office_id = 1,
                            Price = 40.00m,
                            Status = "Available",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Office_id = 2,
                            Price = 41.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Office_id = 1,
                            Price = 42.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Office_id = 2,
                            Price = 43.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            Office_id = 1,
                            Price = 44.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            Office_id = 2,
                            Price = 45.00m,
                            Status = "Available",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Office_id = 1,
                            Price = 46.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            Office_id = 2,
                            Price = 47.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            Office_id = 1,
                            Price = 48.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            Office_id = 2,
                            Price = 49.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            Office_id = 1,
                            Price = 40.00m,
                            Status = "Available",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            Office_id = 2,
                            Price = 41.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            Office_id = 1,
                            Price = 42.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            Office_id = 2,
                            Price = 43.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            Office_id = 1,
                            Price = 44.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            Office_id = 2,
                            Price = 45.00m,
                            Status = "Available",
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            Office_id = 1,
                            Price = 46.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            Office_id = 2,
                            Price = 47.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            Office_id = 1,
                            Price = 48.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            Office_id = 2,
                            Price = 49.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            Office_id = 1,
                            Price = 40.00m,
                            Status = "Available",
                            Type = 1
                        },
                        new
                        {
                            Id = 31,
                            Office_id = 2,
                            Price = 41.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            Office_id = 1,
                            Price = 42.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 33,
                            Office_id = 2,
                            Price = 43.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            Office_id = 1,
                            Price = 44.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            Office_id = 2,
                            Price = 45.00m,
                            Status = "Available",
                            Type = 1
                        },
                        new
                        {
                            Id = 36,
                            Office_id = 1,
                            Price = 46.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 37,
                            Office_id = 2,
                            Price = 47.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 38,
                            Office_id = 1,
                            Price = 48.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 39,
                            Office_id = 2,
                            Price = 49.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 40,
                            Office_id = 1,
                            Price = 40.00m,
                            Status = "Available",
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            Office_id = 2,
                            Price = 41.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 42,
                            Office_id = 1,
                            Price = 42.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 43,
                            Office_id = 2,
                            Price = 43.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 44,
                            Office_id = 1,
                            Price = 44.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 45,
                            Office_id = 2,
                            Price = 45.00m,
                            Status = "Available",
                            Type = 1
                        },
                        new
                        {
                            Id = 46,
                            Office_id = 1,
                            Price = 46.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 47,
                            Office_id = 2,
                            Price = 47.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 48,
                            Office_id = 1,
                            Price = 48.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 49,
                            Office_id = 2,
                            Price = 49.00m,
                            Status = "Available",
                            Type = 0
                        },
                        new
                        {
                            Id = 50,
                            Office_id = 1,
                            Price = 40.00m,
                            Status = "Available",
                            Type = 1
                        });
                });

            modelBuilder.Entity("OfficeFlow.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Warsaw Spire",
                            OpeningHours = "{\"Monday\":\"08:00-18:00\",\"Tuesday\":\"08:00-18:00\",\"Wednesday\":\"08:00-18:00\",\"Thursday\":\"08:00-18:00\",\"Friday\":\"08:00-16:00\",\"Saturday\":\"Closed\",\"Sunday\":\"Closed\"}"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cracow Tower",
                            OpeningHours = "{\"Monday\":\"07:00-20:00\",\"Tuesday\":\"07:00-20:00\",\"Wednesday\":\"07:00-20:00\",\"Thursday\":\"07:00-20:00\",\"Friday\":\"07:00-20:00\",\"Saturday\":\"09:00-15:00\",\"Sunday\":\"Closed\"}"
                        });
                });

            modelBuilder.Entity("OfficeFlow.Models.OfficeAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId")
                        .IsUnique();

                    b.ToTable("OfficeAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "Plac Europejski 1",
                            AddressLine2 = "",
                            City = "Warszawa",
                            OfficeId = 1,
                            PostalCode = "00123",
                            Town = "Mazowieckie"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "Pawia 5",
                            AddressLine2 = "",
                            City = "Kraków",
                            OfficeId = 2,
                            PostalCode = "31154",
                            Town = "Małopolskie"
                        });
                });

            modelBuilder.Entity("OfficeFlow.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Desk_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated_at")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.Property<int>("reservationStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Desk_id");

                    b.HasIndex("User_id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 1,
                            End_date = new DateTime(2026, 5, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 2,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 3,
                            End_date = new DateTime(2026, 6, 21, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 21, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 3,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 4,
                            End_date = new DateTime(2026, 6, 5, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 4,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 5,
                            End_date = new DateTime(2026, 6, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 5,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 6,
                            End_date = new DateTime(2026, 6, 23, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 6,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 7,
                            End_date = new DateTime(2026, 6, 7, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 7,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 8,
                            End_date = new DateTime(2026, 6, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 8,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 9,
                            End_date = new DateTime(2026, 6, 16, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 9,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 10,
                            End_date = new DateTime(2026, 6, 13, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 10,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 11,
                            End_date = new DateTime(2026, 6, 17, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 17, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 11,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 12,
                            End_date = new DateTime(2026, 6, 25, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 12,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 13,
                            End_date = new DateTime(2026, 6, 13, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 13,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 14,
                            End_date = new DateTime(2026, 6, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 14,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 15,
                            End_date = new DateTime(2026, 6, 25, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 15,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 16,
                            End_date = new DateTime(2026, 6, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 16,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 17,
                            End_date = new DateTime(2026, 6, 6, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 17,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 18,
                            End_date = new DateTime(2026, 6, 22, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 18,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 19,
                            End_date = new DateTime(2026, 6, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 7, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 19,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 20,
                            End_date = new DateTime(2026, 6, 10, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 20,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 21,
                            End_date = new DateTime(2026, 6, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 25, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 21,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 22,
                            End_date = new DateTime(2026, 6, 17, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 22,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 23,
                            End_date = new DateTime(2026, 6, 23, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 23,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 24,
                            End_date = new DateTime(2026, 6, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 24,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 25,
                            End_date = new DateTime(2026, 6, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 25,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 26,
                            End_date = new DateTime(2026, 6, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 26,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 27,
                            End_date = new DateTime(2026, 6, 9, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 27,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 28,
                            End_date = new DateTime(2026, 6, 10, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 28,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 29,
                            End_date = new DateTime(2026, 6, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 29,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 30,
                            End_date = new DateTime(2026, 6, 19, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 30,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 31,
                            End_date = new DateTime(2026, 6, 3, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 31,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 32,
                            End_date = new DateTime(2026, 6, 22, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 32,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 33,
                            End_date = new DateTime(2026, 6, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 33,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 34,
                            End_date = new DateTime(2026, 6, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 34,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 35,
                            End_date = new DateTime(2026, 6, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 35,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 36,
                            End_date = new DateTime(2026, 6, 4, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 36,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 37,
                            End_date = new DateTime(2026, 6, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 37,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 38,
                            End_date = new DateTime(2026, 6, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 14, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 38,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 39,
                            End_date = new DateTime(2026, 6, 16, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 39,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 40,
                            End_date = new DateTime(2026, 6, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 26, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 40,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 41,
                            End_date = new DateTime(2026, 6, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 41,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 42,
                            End_date = new DateTime(2026, 6, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 42,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 43,
                            End_date = new DateTime(2026, 6, 28, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 43,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 44,
                            End_date = new DateTime(2026, 6, 15, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 44,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 45,
                            End_date = new DateTime(2026, 6, 19, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 19, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 45,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 46,
                            End_date = new DateTime(2026, 6, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 46,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 47,
                            End_date = new DateTime(2026, 6, 14, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 47,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 48,
                            End_date = new DateTime(2026, 6, 17, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 48,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 1,
                            End_date = new DateTime(2026, 6, 10, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 49,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 2,
                            End_date = new DateTime(2026, 6, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 50,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 3,
                            End_date = new DateTime(2026, 6, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 51,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 4,
                            End_date = new DateTime(2026, 6, 29, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 29, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 52,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 5,
                            End_date = new DateTime(2026, 6, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 53,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 6,
                            End_date = new DateTime(2026, 6, 4, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 54,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 7,
                            End_date = new DateTime(2026, 6, 11, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 55,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 8,
                            End_date = new DateTime(2026, 6, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 56,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 9,
                            End_date = new DateTime(2026, 6, 8, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 57,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 10,
                            End_date = new DateTime(2026, 6, 16, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 58,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 11,
                            End_date = new DateTime(2026, 6, 24, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 59,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 12,
                            End_date = new DateTime(2026, 6, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 60,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 13,
                            End_date = new DateTime(2026, 6, 18, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 61,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 14,
                            End_date = new DateTime(2026, 6, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 62,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 15,
                            End_date = new DateTime(2026, 6, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 63,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 16,
                            End_date = new DateTime(2026, 6, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 64,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 17,
                            End_date = new DateTime(2026, 6, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 9, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 65,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 18,
                            End_date = new DateTime(2026, 6, 8, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 66,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 19,
                            End_date = new DateTime(2026, 6, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 67,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 20,
                            End_date = new DateTime(2026, 6, 30, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 30, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 68,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 21,
                            End_date = new DateTime(2026, 6, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 69,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 22,
                            End_date = new DateTime(2026, 6, 11, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 70,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 23,
                            End_date = new DateTime(2026, 6, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 25, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 71,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 24,
                            End_date = new DateTime(2026, 6, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 72,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 25,
                            End_date = new DateTime(2026, 6, 27, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 27, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 73,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 26,
                            End_date = new DateTime(2026, 6, 28, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 74,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 27,
                            End_date = new DateTime(2026, 6, 10, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 75,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 28,
                            End_date = new DateTime(2026, 6, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 76,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 29,
                            End_date = new DateTime(2026, 6, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 7, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 77,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 30,
                            End_date = new DateTime(2026, 6, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 7, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 78,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 31,
                            End_date = new DateTime(2026, 6, 8, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 79,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 32,
                            End_date = new DateTime(2026, 6, 30, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 80,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 33,
                            End_date = new DateTime(2026, 6, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 81,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 34,
                            End_date = new DateTime(2026, 6, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 7, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 82,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 35,
                            End_date = new DateTime(2026, 6, 18, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 83,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 36,
                            End_date = new DateTime(2026, 6, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 84,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 37,
                            End_date = new DateTime(2026, 6, 19, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 85,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 38,
                            End_date = new DateTime(2026, 6, 27, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 86,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 39,
                            End_date = new DateTime(2026, 6, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 87,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 40,
                            End_date = new DateTime(2026, 6, 15, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 88,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 41,
                            End_date = new DateTime(2026, 6, 29, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 29, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 89,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 42,
                            End_date = new DateTime(2026, 6, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 90,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 43,
                            End_date = new DateTime(2026, 6, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 91,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 44,
                            End_date = new DateTime(2026, 6, 29, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 29, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 92,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 45,
                            End_date = new DateTime(2026, 6, 13, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 93,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 46,
                            End_date = new DateTime(2026, 6, 13, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 94,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 47,
                            End_date = new DateTime(2026, 6, 28, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 95,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 48,
                            End_date = new DateTime(2026, 6, 27, 14, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 27, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 96,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 1,
                            End_date = new DateTime(2026, 6, 11, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 97,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 2,
                            End_date = new DateTime(2026, 6, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 98,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 3,
                            End_date = new DateTime(2026, 6, 25, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 99,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 4,
                            End_date = new DateTime(2026, 6, 10, 15, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 100,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 5,
                            End_date = new DateTime(2026, 6, 17, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1,
                            reservationStatus = 0
                        },
                        new
                        {
                            Id = 101,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 6,
                            End_date = new DateTime(2026, 6, 9, 16, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 6, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2,
                            reservationStatus = 0
                        });
                });

            modelBuilder.Entity("OfficeFlow.Models.ReservationArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeskId")
                        .HasColumnType("integer");

                    b.Property<int>("Desk_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeskId");

                    b.HasIndex("UserId");

                    b.ToTable("ReservationArchives");
                });

            modelBuilder.Entity("OfficeFlow.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jan.k@example.com",
                            First_name = "Jan",
                            Last_name = "Kowalski"
                        },
                        new
                        {
                            Id = 2,
                            Email = "a.nowak@example.com",
                            First_name = "Anna",
                            Last_name = "Nowak"
                        });
                });

            modelBuilder.Entity("AmenityDesk", b =>
                {
                    b.HasOne("OfficeFlow.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeFlow.Models.Desk", null)
                        .WithMany()
                        .HasForeignKey("DesksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeFlow.Models.Desk", b =>
                {
                    b.HasOne("OfficeFlow.Models.Office", "Office")
                        .WithMany("Desks")
                        .HasForeignKey("Office_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("OfficeFlow.Models.OfficeAddress", b =>
                {
                    b.HasOne("OfficeFlow.Models.Office", "Office")
                        .WithOne("Address")
                        .HasForeignKey("OfficeFlow.Models.OfficeAddress", "OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("OfficeFlow.Models.Reservation", b =>
                {
                    b.HasOne("OfficeFlow.Models.Desk", "Desk")
                        .WithMany("Reservations")
                        .HasForeignKey("Desk_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("OfficeFlow.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Desk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OfficeFlow.Models.ReservationArchive", b =>
                {
                    b.HasOne("OfficeFlow.Models.Desk", "Desk")
                        .WithMany()
                        .HasForeignKey("DeskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeFlow.Models.User", "User")
                        .WithMany("ReservationArchives")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OfficeFlow.Models.Desk", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("OfficeFlow.Models.Office", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Desks");
                });

            modelBuilder.Entity("OfficeFlow.Models.User", b =>
                {
                    b.Navigation("ReservationArchives");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
