// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace OfficeFlow.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330220908_FixedAddresMigration")]
    partial class FixedAddresMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmenityDesk", b =>
                {
                    b.Property<int>("AmenitiesId")
                        .HasColumnType("integer");

                    b.Property<int>("DesksId")
                        .HasColumnType("integer");

                    b.HasKey("AmenitiesId", "DesksId");

                    b.HasIndex("DesksId");

                    b.ToTable("AmenityDesk");

                    b.HasData(
                        new
                        {
                            AmenitiesId = 1,
                            DesksId = 1
                        },
                        new
                        {
                            AmenitiesId = 2,
                            DesksId = 1
                        },
                        new
                        {
                            AmenitiesId = 1,
                            DesksId = 2
                        });
                });

            modelBuilder.Entity("OfficeFlow.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Monitor 4K"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Regulowane biurko"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fotel ergonomiczny"
                        });
                });

            modelBuilder.Entity("OfficeFlow.Models.Desk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Office_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Office_id");

                    b.ToTable("Desks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Office_id = 1,
                            Price = 50.00m,
                            Status = "Active",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Office_id = 1,
                            Price = 100.00m,
                            Status = "Active",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Office_id = 2,
                            Price = 60.00m,
                            Status = "Active",
                            Type = 0
                        });
                });

            modelBuilder.Entity("OfficeFlow.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Warsaw Spire",
                            OpeningHours = "{\"Monday\":\"08:00-18:00\",\"Tuesday\":\"08:00-18:00\",\"Wednesday\":\"08:00-18:00\",\"Thursday\":\"08:00-18:00\",\"Friday\":\"08:00-16:00\",\"Saturday\":\"Closed\",\"Sunday\":\"Closed\"}"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cracow Tower",
                            OpeningHours = "{\"Monday\":\"07:00-20:00\",\"Tuesday\":\"07:00-20:00\",\"Wednesday\":\"07:00-20:00\",\"Thursday\":\"07:00-20:00\",\"Friday\":\"07:00-20:00\",\"Saturday\":\"09:00-15:00\",\"Sunday\":\"Closed\"}"
                        });
                });

            modelBuilder.Entity("OfficeFlow.Models.OfficeAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId")
                        .IsUnique();

                    b.ToTable("OfficeAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "Plac Europejski 1",
                            AddressLine2 = "",
                            City = "Warszawa",
                            OfficeId = 1,
                            PostalCode = "00123",
                            Town = "Mazowieckie"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "Pawia 5",
                            AddressLine2 = "",
                            City = "Kraków",
                            OfficeId = 2,
                            PostalCode = "31154",
                            Town = "Małopolskie"
                        });
                });

            modelBuilder.Entity("OfficeFlow.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Desk_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated_at")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Desk_id");

                    b.HasIndex("User_id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 1,
                            End_date = new DateTime(2026, 5, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 1
                        });
                });

            modelBuilder.Entity("OfficeFlow.Models.ReservationArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Desk_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Desk_id");

                    b.HasIndex("User_id");

                    b.ToTable("ReservationArchives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            Desk_id = 3,
                            End_date = new DateTime(2026, 5, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            Start_date = new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Updated_at = new DateTime(2026, 3, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            User_id = 2
                        });
                });

            modelBuilder.Entity("OfficeFlow.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jan.k@example.com",
                            First_name = "Jan",
                            Last_name = "Kowalski"
                        },
                        new
                        {
                            Id = 2,
                            Email = "a.nowak@example.com",
                            First_name = "Anna",
                            Last_name = "Nowak"
                        });
                });

            modelBuilder.Entity("AmenityDesk", b =>
                {
                    b.HasOne("OfficeFlow.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeFlow.Models.Desk", null)
                        .WithMany()
                        .HasForeignKey("DesksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeFlow.Models.Desk", b =>
                {
                    b.HasOne("OfficeFlow.Models.Office", "Office")
                        .WithMany("Desks")
                        .HasForeignKey("Office_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("OfficeFlow.Models.OfficeAddress", b =>
                {
                    b.HasOne("OfficeFlow.Models.Office", "Office")
                        .WithOne("Address")
                        .HasForeignKey("OfficeFlow.Models.OfficeAddress", "OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("OfficeFlow.Models.Reservation", b =>
                {
                    b.HasOne("OfficeFlow.Models.Desk", "Desk")
                        .WithMany("Reservations")
                        .HasForeignKey("Desk_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("OfficeFlow.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Desk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OfficeFlow.Models.ReservationArchive", b =>
                {
                    b.HasOne("OfficeFlow.Models.Desk", "Desk")
                        .WithMany("ReservationArchives")
                        .HasForeignKey("Desk_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("OfficeFlow.Models.User", "User")
                        .WithMany("ReservationArchives")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Desk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OfficeFlow.Models.Desk", b =>
                {
                    b.Navigation("ReservationArchives");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("OfficeFlow.Models.Office", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Desks");
                });

            modelBuilder.Entity("OfficeFlow.Models.User", b =>
                {
                    b.Navigation("ReservationArchives");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
